version: "3.9"

services: 
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile/Dockerfile
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - ../src:app
      - ../package*.json:/app/
    command: ["npm", "run", "dev"]