version: "3.9"

services: 
  frontend:
    build:
      contecxt: .
      dockerfile: dockerfile
    container_name: react-app
    ports:
      - "5173:5173"
    volumes:
      - ./FrontEnd/react-app:/app
    command: ["npm", "run", "dev"]